
### * State-space models

General:

\[
\begin{aligned}
Y_t &= G_t\textbf{X}_t + W_t \hspace{14mm} \{\textbf{W}_t\} &\sim \text{WN}\left(\textbf{0},\{R_t\}\right) \\
\mathbf{X}_{t+1} &= F_t\mathbf{X}_t + \mathbf{V}_{t} \hspace{15mm} \{\textbf{V}_t\} &\sim \text{WN}\left(\textbf{0},\{Q_t\}\right)
\end{aligned}
\]

When F, G, R and Q are time independent:

\[
\begin{aligned}
Y_t &= G\textbf{X}_t + W_t \hspace{14mm} \{W_t\} &\sim 
\text{WN}\left(\textbf{0},R\right) \\
\mathbf{X}_{t+1} &= F\mathbf{X}_t + \mathbf{V}_{t} \hspace{15mm} \{\mathbf{V}_t\} &\sim \text{WN}\left(\textbf{0},Q\right)
\end{aligned}
\]

### * SARIMA

A SARIMA model is an extended version of the ARIMA model which can also consider a seasonal component in a time series. 
Its general form 

\[
SARIMA(p,d,q)\times(P,D,Q)_{s}
\]

is a seasonal ARIMA process with period $s$ and is written as  

\[
\phi(B)\Phi\left(B^S\right)Y_t = \theta(B)\Theta\left(B^S\right)Z_t, \hspace{7mm}   \{Z_t\}\sim \text{WN}(0,\sigma^2)
\]

if the differenced series $Y_t = (1-B)^d(1-B^s)^D X_t$ is a causal ARMA process defined as above.
Here,
$\phi(z)=1-\phi_1z-...-\phi_pz^p$, $\Phi(z)=1-\Phi_1z-...-\Phi_Pz^P$,
$\theta(z)=1+\theta_1z+...+\theta_qz^q$ and $\Theta(z)=1+\Theta_1z+...+\Theta_Qz^Q$.

The SARIMA model has two parts: A seasonal component and a non-seasonal component.
$(P,D,Q)$ is the ARIMA model between each season and is the seasonal component of the SARIMA model. This part models behaviour for for instance the January months in a time series with monthly observations and where the season is a year long. $(p,d,q)$ is the non-seasonal part of the model and is an ARIMA model _within_ each season.
The interpretation of $p,d,q,P,d$ and $Q$ are known from previous knowledge on the ARIMA models, and $B$ is the backshift operator as before.


## 